name: Maintain docker images in ECR repo

on:
  workflow_dispatch:

jobs:
  pull_push_images:
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker Image and Push to ECR
      run: |
        which curl
        which jq
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region us-east-1

        content=$(curl -sS "https://hub.docker.com/v2/repositories/browsers/edge/tags")
        version=`echo $content | jq -r '.results[1].name'`
        echo 'Latest Edge version is $version'
        docker pull docker.io/browsers/edge:$version
        docker tag docker.io/browsers/edge:$version               public.ecr.aws/orienlabs/browsers/edge:$version
        docker tag docker.io/browsers/edge:$version               public.ecr.aws/orienlabs/browsers/edge:latest
        docker push public.ecr.aws/orienlabs/browsers/edge:$version
        docker push public.ecr.aws/orienlabs/browsers/edge:latest

        docker pull docker.io/aerokube/selenoid-ui:${{ vars.SELENOID_UI_VERSION }}
        docker pull docker.io/aerokube/selenoid:${{ vars.SELENOID_VERSION }}
        docker pull docker.io/aerokube/ggr-ui:${{ vars.GGR_UI_VERSION }}
        docker pull docker.io/aerokube/ggr:${{ vars.GGR_VERSION }}
        docker pull docker.io/selenoid/video-recorder:${{ vars.RECORDER_VERSION }}
        
        docker pull docker.io/browsers/firefox:${{ vars.FIREFOX_VERSION }}
        docker pull docker.io/browsers/chrome:${{ vars.CHROME_VERSION }}
        docker pull docker.io/browsers/opera:${{ vars.OPERA_VERSION }}
        docker pull docker.io/browsers/safari:${{ vars.SAFARI_VERSION }}

        docker tag docker.io/aerokube/selenoid-ui:${{ vars.SELENOID_UI_VERSION }} public.ecr.aws/orienlabs/selenoid-ui:${{ vars.SELENOID_UI_VERSION }}
        docker tag docker.io/aerokube/selenoid:${{ vars.SELENOID_VERSION }}       public.ecr.aws/orienlabs/selenoid:${{ vars.SELENOID_VERSION }}
        docker tag docker.io/aerokube/ggr-ui:${{ vars.GGR_UI_VERSION }}           public.ecr.aws/orienlabs/ggr-ui:${{ vars.GGR_UI_VERSION }}
        docker tag docker.io/aerokube/ggr:${{ vars.GGR_VERSION }}                 public.ecr.aws/orienlabs/ggr:${{ vars.GGR_VERSION }}
        docker tag docker.io/selenoid/video-recorder:${{ vars.RECORDER_VERSION }} public.ecr.aws/orienlabs/video-recorder:${{ vars.RECORDER_VERSION }}
        
        docker tag docker.io/browsers/firefox:${{ vars.FIREFOX_VERSION }}         public.ecr.aws/orienlabs/browsers/firefox:${{ vars.FIREFOX_VERSION }}
        docker tag docker.io/browsers/chrome:${{ vars.CHROME_VERSION }}           public.ecr.aws/orienlabs/browsers/chrome:${{ vars.CHROME_VERSION }}
        docker tag docker.io/browsers/opera:${{ vars.OPERA_VERSION }}             public.ecr.aws/orienlabs/browsers/opera:${{ vars.OPERA_VERSION }}
        docker tag docker.io/browsers/safari:${{ vars.SAFARI_VERSION }}           public.ecr.aws/orienlabs/browsers/safari:${{ vars.SAFARI_VERSION }}

        docker tag docker.io/aerokube/selenoid-ui:${{ vars.SELENOID_UI_VERSION }} public.ecr.aws/orienlabs/selenoid-ui:latest
        docker tag docker.io/aerokube/selenoid:${{ vars.SELENOID_VERSION }}       public.ecr.aws/orienlabs/selenoid:latest
        docker tag docker.io/aerokube/ggr-ui:${{ vars.GGR_UI_VERSION }}           public.ecr.aws/orienlabs/ggr-ui:latest
        docker tag docker.io/aerokube/ggr:${{ vars.GGR_VERSION }}                 public.ecr.aws/orienlabs/ggr:latest
        docker tag docker.io/selenoid/video-recorder:${{ vars.RECORDER_VERSION }} public.ecr.aws/orienlabs/video-recorder:latest
        
        docker tag docker.io/browsers/firefox:${{ vars.FIREFOX_VERSION }}         public.ecr.aws/orienlabs/browsers/firefox:latest
        docker tag docker.io/browsers/chrome:${{ vars.CHROME_VERSION }}           public.ecr.aws/orienlabs/browsers/chrome:latest
        docker tag docker.io/browsers/opera:${{ vars.OPERA_VERSION }}             public.ecr.aws/orienlabs/browsers/opera:latest
        docker tag docker.io/browsers/safari:${{ vars.SAFARI_VERSION }}           public.ecr.aws/orienlabs/browsers/safari:latest


        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/orienlabs
        
        docker push public.ecr.aws/orienlabs/selenoid-ui:${{ vars.SELENOID_UI_VERSION }} 
        docker push public.ecr.aws/orienlabs/selenoid:${{ vars.SELENOID_VERSION }}       
        docker push public.ecr.aws/orienlabs/ggr-ui:${{ vars.GGR_UI_VERSION }} 
        docker push public.ecr.aws/orienlabs/ggr:${{ vars.GGR_VERSION }}       
        docker push public.ecr.aws/orienlabs/video-recorder:${{ vars.RECORDER_VERSION }} 
         
        docker push public.ecr.aws/orienlabs/browsers/firefox:${{ vars.FIREFOX_VERSION }}  
        docker push public.ecr.aws/orienlabs/browsers/chrome:${{ vars.CHROME_VERSION }}  
        docker push public.ecr.aws/orienlabs/browsers/opera:${{ vars.OPERA_VERSION }}    
        docker push public.ecr.aws/orienlabs/browsers/safari:${{ vars.SAFARI_VERSION }}  
        docker push public.ecr.aws/orienlabs/selenoid-ui:latest                         
        docker push public.ecr.aws/orienlabs/selenoid:latest       
        docker push public.ecr.aws/orienlabs/ggr-ui:latest                         
        docker push public.ecr.aws/orienlabs/ggr:latest                            
        docker push public.ecr.aws/orienlabs/video-recorder:latest                      
                           
        docker push public.ecr.aws/orienlabs/browsers/firefox:latest                    
        docker push public.ecr.aws/orienlabs/browsers/chrome:latest                     
        docker push public.ecr.aws/orienlabs/browsers/opera:latest                      
        docker push public.ecr.aws/orienlabs/browsers/safari:latest
